### ISSUE TITLE
Error running test-anything on macOS 10.13.5 (High Sierra)

### ISSUE THREAD

**Issue by ghost** [workshopper/test-anything#36]
node: v10.6.0
npm: 6.1.0
installed with nvm: 0.33.11

Output of npm v test-anything:

```
npm v test-anything   

test-anything@1.1.7 | MIT | deps: 6 | versions: 13
Learn to test anything with TAP
https://github.com/finnp/test-anything

keywords: nodeschool, workshopper, learn, cli, tap

bin: test-anything

dist
.tarball https://registry.npmjs.org/test-anything/-/test-anything-1.1.7.tgz
.shasum: 623da2407f78e55ea65852b9d18c5ed9602596f0

dependencies:
adventure-verify: ^2.2.0     adventure: ^2.11.0           cli-md: ^1.0.0               concat-stream: ^1.4.8        tape: ^4.0.0                 workshopper-exercise: ^2.3.0 

maintainers:
- finnpauls <derfinn@gmail.com>

dist-tags:
latest: 1.1.7  

published a year ago by finnpauls <derfinn@gmail.com>
```

* * *

When trying to open test-anything, everything seemingly runs fine, but as soon as I select one of the exercises I get an error.

```
fs.js:133
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1132:14)
    at Shop.save (/Users/martin/.nvm/versions/node/v10.6.0/lib/node_modules/test-anything/node_modules/adventure/index.js:288:8)
    at Shop.select (/Users/martin/.nvm/versions/node/v10.6.0/lib/node_modules/test-anything/node_modules/adventure/index.js:246:10)
    at EventEmitter.<anonymous> (/Users/martin/.nvm/versions/node/v10.6.0/lib/node_modules/test-anything/node_modules/adventure/index.js:278:14)
    at EventEmitter.emit (events.js:182:13)
    at Menu.<anonymous> (/Users/martin/.nvm/versions/node/v10.6.0/lib/node_modules/test-anything/node_modules/adventure/lib/menu.js:49:22)
    at Menu.emit (events.js:182:13)
    at Menu.ondata [as _ondata] (/Users/martin/.nvm/versions/node/v10.6.0/lib/node_modules/test-anything/node_modules/terminal-menu/index.js:215:18)
    at DestroyableTransform._transform (/Users/martin/.nvm/versions/node/v10.6.0/lib/node_modules/test-anything/node_modules/terminal-menu/index.js:50:18)
```

**Comment by finnp** [comment]
Thanks for the report. I haven't updated it for newer node versions yet. So running node 8 would work.
